config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  	resources :posts do
  		resources :comments
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true, length: {minimum: 4}
	validates :body, presence: true, length: {minimum: 7}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale

 	private

	def set_locale
  		I18n.locale = params[:locale] || I18n.default_locale
	end

	def default_url_options(options = {})
		{ locale: I18n.locale }.merge options
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us'
		@content = 'This is the about page'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [ :index, :show ]

	def new
		@post = Post.new
	end

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if (@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	def change_locale
		if I18n.locale = 'en'
			change_locale_ru
		else
			change_locale_en
		end
	end

	private def change_locale_en
		I18n.locale = 'en'
    	file_dir = Rails.root.join('config', 'locales', 'en.yml').to_s
    	file = YAML.load_file(file_dir)
    	@swch_lang = "Русский"
    end

    private def change_locale_ru
    	I18n.locale = 'ru'
    	file_dir = Rails.root.join('config', 'locales', 'ru.yml').to_s
    	file = YAML.load_file(file_dir)
    	@swch_lang = "English"
    end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
  	{ success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info",
  	}[name.to_sym] || name
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0"><%= t('comments') %></h6>
    <% @post.comments.each do |comment| %>
		  <div class="media pt-3">
    		<svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
   			<p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
       		<strong class="d-block text-gray-dark"><%= comment.username %></strong>
       		<%= comment.body %>
          <%= link_to '[X]', [comment.post, comment], method: :delete, data: {confirm: t('sure') } %>
   			</p>
   		</div>
    <% end %>
   	<small class="d-block text-right mt-3">
   		<a href="#"><%= t('updates') %></a>
	  </small>
</div>

app/views/comments/_form.html.erb
<h4><%= t('add_comment') %></h4>
	<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<a class="form_title">Username:</a>
		<%= f.text_field(:username, {:class => 'form_control'})  %>
	</p>
	<p>
		<a class="form_title"><%= t('post') %></a><br>
		<%= f.text_area(:body, {:class => 'form_control'}) %>
	</p>
	<p>
		<%= f.submit(t('submit'), {:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gleb's Blog</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md bg-light fixed-top">
      <a class="blog-header-logo navbar-brand" href="#" id=logo><%= t('logo') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div>
        <a class="p-2 text" href="#"><%= link_to t('home'), home_path %></a>
        <a class="p-2 text" href="#"><%= link_to t('create_post'), new_post_path %></a>
        <% if user_signed_in? %>
          <a class="p-2 text" href="#"><%= link_to t('signout'), destroy_user_session_path, method: :delete %></a>
        <% else %>
          <a class="p-2 text" href="#"><%= link_to t('signin'), new_user_session_path %></a>
          <a class="p-2 text" href="#"><%= link_to t('signup'), new_user_registration_path %></a>
        <% end %>
        <a class="p-2 text<%= ' active' if I18n.locale == :en %>"><%= link_to "Рус", { locale: :ru } %></a>
        <a class="p-2 text<%= ' active' if I18n.locale == :ru %>"><%= link_to "Eng", { locale: :en } %></a>
      </div>
    </nav>
    <div class="col-md-12">
      <% flash.each do |name, message| %>
        <div class="alert <%= bootstrap_class_for(name) %>">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<div class="container">	
	<h1><%= t('edit_post') %></h1>
	<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |msg| %>
				<div class="alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>
		<p>
			<a class="form_title"><%= t('title') %></a><br>
			<%= f.text_field(:title, {:class => 'form_control'})  %>
		</p>
		<p>
			<a class="form_title"><%= t('post') %></a><br>
			<%= f.text_area(:body, {:class => 'form_control'}) %>
		</p>
		<p>
			<%= f.submit(t('submit'), {:class => 'btn btn-primary'}) %>
		</p>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="container">    
    <h1><%= t('blog_posts') %></h1>
    <% @posts.each do |post| %>
	   <div class="card flex-md-row mb-4 shadow-sm h-md-250 border">
            <div class="card-body d-flex flex-column align-items-start">
        	   <strong class="d-inline-block mb-2 text-primary">World</strong>
        	   <h3 class="mb-0"><a class="text-dark title" href="#"><%= post.title %></a></h3>
        	   <div class="mb-1 text-muted"><%= post.created_at.to_date.strftime("%d %B, %Y") %></div>
        	   <p class="card-text mb-auto"><%= post.body %></p>
        	   <%= link_to t('read_more'), post_path(post), :class => 'btn btn-default' %>
    	   </div>
        </div>
    <% end %> 
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1><%= t('add_post') %></h1>
	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |msg| %>
				<div class="alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>
		<p>
			<a class="form_title"><%= t('title') %></a><br>
			<%= f.text_field(:title, {:class => 'form_control'})  %>
		</p>
		<p>
			<a class="form_title"><%= t('post') %></a><br>
			<%= f.text_area(:body, {:class => 'form_control'}) %>
		</p>
		<p>
			<%= f.submit(t('submit'), {:class => 'btn btn-primary'}) %>
		</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="jumbotron p-3 p-md-5 text-white bg-dark">
    <div class="col-md-6 px-0">
    	<h2 class="display-4 font-italic title"><%= @post.title %></h2>
    	<p class="lead my-3"><%= @post.body %></p>
    	<hr>
    	<%= link_to t('edit'), edit_post_path(@post), :class => 'btn btn-default' %>
		<%= link_to t('delete'), post_path(@post), method: :delete, 
											data: {confirm: t('sure') }, 
											:class => 'btn btn-danger' %>
    </div>
</div>

<hr>
<div class="container">
	<%= render 'comments/comments' %>
	<hr>
	<%= render 'comments/form' %>
</div>